# yaml-language-server: $schema=https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json
upgrade:
  source: cdn
  interval: 168h
  auto: false
  notice: false
final_space: true
transient_prompt:
  background: transparent
  foreground: "#626262"
  template: "~>"
  filler: "-"
blocks:
  - type: prompt
    alignment: left
    segments:
      - template: '{{ .UserName }}@{{ .HostName }}'
        foreground: '#cdcdcd'
        type: text
        style: plain
      - properties:
          style: folder
        template: ' {{ .PWD }} '
        foreground: '#bebeda'
        type: path
        style: plain
      - type: git
        style: plain
        foreground: "#6e94b2"
        template: "{{ .HEAD }}"
        properties:
          fetch_status: false
      - type: git
        style: plain
        foreground: "#99b782"
        template: "{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}"
        properties:
          fetch_status: true
          source: cli
      - type: git
        style: plain
        foreground: "#626262"
        template: "{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}"
        properties:
          fetch_status: true
          source: cli
      - template: ' X '
        foreground: '#d8647e'
        type: status
        style: plain
  - type: prompt
    alignment: right
    segments:
      - type: executiontime
        style: text
        foreground: "#f5cb96"
        template: " {{ .FormattedMs }} "
        properties:
          threshold: 1
          style: austin
          always_enabled: true
  - type: prompt
    alignment: left
    newline: true
    segments:
      - type: python
        style: plain
        foreground: "#cdcdcd"
        template: "  {{ if .Error }}{{ .Error }}{{ else }}{{ if .Venv }}{{ .Venv }} {{ end }}{{ .Full }}{{ end }} "
      - template: ❯
        foreground: '#606079'
        type: text
        style: plain
version: 3
